[package]
name = "xinput-json"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.150"
num-derive = "0.4.1"
num-traits = "0.2.17"
serde = { version = "1.0.193", features = ["derive"] }
x11 = { version = "2.21.0", features = ["xlib", "xinput"] }
