[package]
name = "xinput-json"
version = "0.3.3"
edition = "2021"

[dependencies]
num-derive = "0.4.1"
num-traits = "0.2.17"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
x11 = { version = "2.21.0", features = ["xlib", "xinput"] }
