name: "build and release"
on:
  release:
    types: [created, edited]

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        install_url: https://releases.nixos.org/nix/nix-2.17.1/install
        extra_nix_config: "experimental-features = nix-command flakes fetch-closure"
    - uses: cachix/cachix-action@v12
      with:
        name: chezbryan
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: ./build.sh --dry-run
    - run: ./build.sh
    - uses: svenstaro/upload-release-action@v2
      with:
        # repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: result/bin/xinput-json
        overwrite: true
